@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>UmlPostProcessors\n<size:10>nl.talsmasoftware.umldoclet.uml.util" as nl.talsmasoftware.umldoclet.uml.util.UmlPostProcessors [[UmlPostProcessors.html]] {
        +javaBeanPropertiesAsFieldsPostProcessor(): Consumer<Type>
    }

    center footer UMLDoclet 2.0.14, PlantUML 1.2021.9
@enduml
