@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PackageDiagram\n<size:10>nl.talsmasoftware.umldoclet.uml" as nl.talsmasoftware.umldoclet.uml.PackageDiagram [[PackageDiagram.html]] {
        +PackageDiagram(Configuration, String)
        #getPlantUmlFile(): File
    }

    abstract class "<size:14>Diagram\n<size:10>nl.talsmasoftware.umldoclet.uml" as nl.talsmasoftware.umldoclet.uml.Diagram [[Diagram.html]] {
        {abstract} #getPlantUmlFile(): File
    }

    nl.talsmasoftware.umldoclet.uml.Diagram <|-- nl.talsmasoftware.umldoclet.uml.PackageDiagram

    center footer UMLDoclet 2.0.14, PlantUML 1.2021.9
@enduml
