@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>Type\n<size:10>nl.talsmasoftware.umldoclet.uml" as nl.talsmasoftware.umldoclet.uml.Type [[Type.html]] {
        +Type(Namespace, Classification, TypeName)
        +getName(): TypeName
        +updateGenericTypeVariables(TypeName): void
        +deprecated(): Type
        +setIncludePackagename(boolean): void
        +getPackagename(): String
        +getClassfication(): Classification
        +writeTo(IPW extends IndentingPrintWriter): IPW extends IndentingPrintWriter
        +writeChildrenTo(IPW extends IndentingPrintWriter): IPW extends IndentingPrintWriter
    }

    abstract class "<size:14>UMLNode\n<size:10>nl.talsmasoftware.umldoclet.uml" as nl.talsmasoftware.umldoclet.uml.UMLNode [[UMLNode.html]] {
        {abstract} #writeTo(IPW extends IndentingPrintWriter): IPW extends IndentingPrintWriter
    }
    enum "<size:14>Type.Classification\n<size:10>nl.talsmasoftware.umldoclet.uml" as nl.talsmasoftware.umldoclet.uml.Type.Classification [[Type.Classification.html]]

    nl.talsmasoftware.umldoclet.uml.UMLNode <|-- nl.talsmasoftware.umldoclet.uml.Type
    nl.talsmasoftware.umldoclet.uml.Type +-- nl.talsmasoftware.umldoclet.uml.Type.Classification

    center footer UMLDoclet 2.0.14, PlantUML 1.2021.9
@enduml
